[tools]
lua = "5.1"
node = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@css-modules-kit/ts-plugin" = "latest"
"npm:commitizen" = "latest"
"npm:cz-conventional-changelog" = "latest"
"npm:graphql-language-service-cli" = "latest"
"npm:pnpm" = "latest"
